### ISSUE TITLE
"external-link"  the same ones are deleted ?

### ISSUE THREAD

**Issue by lavara123** [stkevintan/canoe-blog#3]
when the "identifiers" are the same

example:

**config.toml**
```toml
[[menu.social]]
  pre = "<svg class='svg-icons svg-icons-github'><use xlink:href='#svg-icons-github'></use></svg>"
  name = "Github"
  identifier = "@stkevintan"
  url = "https://github.com/stkevintan"

[[menu.social]]
  pre = "<svg class='svg-icons svg-icons-twitter'><use xlink:href='#svg-icons-twitter'></use></svg>"
  name = "Twitter"
  identifier = "@stkevintan"
  url = "https://twitter.com/kevinsfork"
```

output:
Github

(twitter deleted)

need to fix "**layouts/partials/slidebar.html**"

```html
    <ul class="nav-group external-link">
      {{ with .Site.Menus.social }} {{ range . }}
      <li>
        <a class="collapsible-header waves-effect waves-indigo" href="{{.URL}}" target="_blank">
          {{ .Pre | default ("<i class='material-icons'>language</i>" | safeHTML ) }}
          <span class="content">{{ .Name }}<small>{{ .Identifier }}</small></span>
          <i class="material-icons">chevron_right</i>
        </a>
      </li>
      {{ end }} {{ end }}
    </ul>
```
